### ISSUE TITLE
树莓派+docker lovelace配置路径怎样写?

### ISSUE THREAD

**Issue by vvss** [cnk700i/ha_modified_components#1]
树莓派+docker+hass.io
尝试过
目录结构是这样的
Home Assistant/homeassistant/custom_components/
尝试过这样

url: /homeassistant/www/custom-lovelace/hf_weather-card/hf_weather-more-info.js

url: /local/www/custom-lovelace/hf_weather-card/hf_weather-more-info.js

证书是这样写的可以正常调用
Home Assistant/ssl
  ssl_key: /ssl/privkey.pem
请问该怎么写,谢谢!

**Comment by cnk700i** [comment]
配置文件里url不是真实地址的，/local映射到真实的{配置目录}/www：比如{配置目录}/abc/123.js，那url就是/local/abc/123.js
