### ISSUE TITLE
Platform error weather.hf_weather - Integration 'hf_weather' not found.

### ISSUE THREAD

**Issue by Wing-Sing** [cnk700i/ha_modified_components#18]
如题，不知道为什么

**Comment by ettingshausen** [comment]
Similar to https://github.com/morestart/HeWeather/issues/5
> solution: [#17](https://github.com/ee02217/homeassistant-mi-heater/issues/17)
1. 安装插件，重启。
2. 修改`configuration.yaml`，重启
