### ISSUE TITLE
小时预报不能正确显示

### ISSUE THREAD

**Issue by HarryChen55** [cnk700i/ha_modified_components#4]
运行环境：群晖docker
Home Assistant版本：0.93.2

Configuration.yaml配置：
weather:
  - platform: hf_weather
    name: HeFeng_Weather
    city: CN101280604
    appkey:xxxxxxxxxxxxxxxxxxxxxx

Lovelace配置：
resources:
  - type: module
    url: /local/custom-lovelace/hf_weather-card/hf_weather-card.js
  - type: module
    url: /local/custom-lovelace/hf_weather-card/hf_weather-more-info.js
title: Home
views:
    cards:
      - entity: weather.hefeng_weather
        icons: /local/custom-lovelace/hf_weather-card/icons/static/
        title: Weather Forecast
        type: 'custom:hf_weather-card'

![屏幕快照 2019-06-25 下午4 01 05](https://user-images.githubusercontent.com/15730821/60081477-66e02480-9764-11e9-857e-f8d24ae2eb22.png)

**Comment by cnk700i** [comment]
感觉是浏览器兼容性问题，我用chrome显示没问题。。

**Comment by cnk700i** [comment]
已解决
